### PR TITLE
[DS3231.cpp]: Remove Compiler Warnings!

### PR DESCRIPTION
**Pull request by hasenradball**
Remove of simple Compiler Warnings (#39)

### CODE REVIEW

**Comment by awickert** [comment]
Looks great; thanks! If you can confirm that all compiler warnings are now gone (and/or give me sample code to test here), I will create a new release.

**Comment by hasenradball** [comment]
Hi,
two ones are left:
1) line 158 in the cpp file
`static uint8_t bin2bcd (uint8_t val) { return val + 6 * (val / 10); }`
```
X:\libraries\DS3231\DS3231.cpp: At global scope:
X:\libraries\DS3231\DS3231.cpp:158:16: warning: 'uint8_t bin2bcd(uint8_t)' defined but not used [-Wunused-function]
 static uint8_t bin2bcd (uint8_t val) { return val + 6 * (val / 10); }
```

2) line 138 in cpp file:
```
static uint8_t conv2d(const char* p) {
    uint8_t v = 0;
    if ('0' <= *p && *p <= '9')
        v = *p - '0';
    return 10 * v + *++p - '0';
}
```
```
X:\libraries\DS3231\DS3231.cpp:138:16: warning: 'uint8_t conv2d(const char*)' defined but not used [-Wunused-function]
 static uint8_t conv2d(const char* p) {
```

Can you give me a feedback if these could be used in the future?
I am not sure.
If you say I can delete it I will make an additional PR and then you can make a new release.

Both (conv2d and bin2bcd) are actually not used anymore in the cpp file.

I will wait for your feedback, what to do.

Thanks Frank

**Comment by awickert** [comment]
Hallo Frank,

It does not seem to be used and I'm not sure why it is there! My past self probably knows.

I have deleted it and pushed: 095a449a4af25d0da32e57f14a4f468204f42155

The header file was also #include-ing a old version of the time library; I have updated this as well: 095a449a4af25d0da32e57f14a4f468204f42155

I also have noted that many examples are out of date with modern Arduino naming conventions, and will fix these as able.

Therefore, I will probably try to update everything before pushing a larger v1.1.0 update.

Best wishes,
Andy

**Comment by hasenradball** [comment]
Hi Andy,

I saw you deleted only one of two unused warnings.
Did you forget the second?
So I understood I am finished, right?
If you need anything from my side, let me know.

Best wishes Frank

**Comment by awickert** [comment]
Thanks, Frank! It was late at night for me :)
703bc4ea7ea66be90c39c5b907a7c54b97f80d00
And your help is much appreciated. You've prodded me to start giving this library some much-needed love.

**Pull request merged**
