### PR TITLE
Prepare tag for the 1.1.2 release

### PR DESCRIPTION
**Pull request by designer2k2**
Tag 1.1.2 preparation

See the discussion here: https://github.com/NorthernWidget/DS3231/pull/79

### CODE REVIEW

**Comment by IowaDave** [comment]
@designer2k2 

Merging this PR #83 now. It will update the library.preferences file. Then I will create a new tag 1.1.2 and publish it as the new "current version".

My understanding is that doing so will create a new .zip file containing the correct version number, 1.1.2. With that being done, we expect the Library Manager to offer 1.1.2 as the latest version for the library listed as "DS3231".

Thanks for your help and please stay in touch with this process. Let's check progress and determine next steps soon.

David

**Comment by IowaDave** [comment]
@designer2k2 

The new tag 1.1.2 is published as the new current version, at 2210 GMT 20March2023 (5:10 p.m. in central U.S.)

**Comment by IowaDave** [comment]
@designer2k2 

I followed the links to the other repo, the one calling itself "DS3231_RTC". Glancing through the file list and skimming visually through the README file it looks like a verbatim copy of Andrew's repo. Two factual matters with this repo that I think ought to be of concern to the Arduino community:

1. In the library.properties file, a change was made to the "author" declaration. The name "Affan Hanif" was inserted first, ahead of Andrew's, as the author. This claim looks doubtful, as there is no evidence of any change to the content compared to the content of Andrew's repo version 1.1.0, as it stood at the time of copying.
2. In the list of public repos (16 of them) in the github account, [https://github.com/affanhanifathtarech/](https://github.com/affanhanifathtarech/), some disclose that they are forks from other repos. However, the "DS3231_RTC" repo omits this disclosure.

It looks like bad behavior to me. Worse, the similarity of names and content creates the potential for confusion when people go looking for the DS3231 library, as well as reputational risk for Andrew Wickert. Mr. Hanif, if that is is name, should not use Mr. Wickert's name in the Arduino Library Manager entry for a repo that he falsely publishes as if it were his own work. 

How do we go about raising these concerns with the Arduino community?

**Comment by IowaDave** [comment]
@designer2k2 

It looks like the most straightforward approach is to submit a PR to remove the url from the list. It's on line 5301 at the time of writing. The justification could include the comments mentioned previously. 

Your thoughts?

**Comment by IowaDave** [comment]
@designer2k2

Version 1.1.2 is now active in the Library Manager. And I learned some skills in the process.

Thanks!

Let's discuss the duplicative repo soon. Hope to hear your thoughts on that.

**Comment by designer2k2** [comment]
Hello @IowaDave,
that worked like a charm, all is correct now and a functional [1.1.2](https://github.com/NorthernWidget/DS3231/releases/tag/v1.1.2) is out! Also the pde -> ino change is included, nice!

For the [1.1.2](https://github.com/NorthernWidget/DS3231/releases/tag/v1.1.2) Release lets now see the next days/weeks if any new issues get raised.

The other repo should at least be discussed with the Arduino team. For me it is also not ok to claim first place author and hiding that its a fork with no changes.
For that i would suggest raising a "Library Removal" PR on the library-registry, removing the line 5301 (Example: https://github.com/arduino/library-registry/pull/2314).
Stating all the points you mentioned, and then see how it goes. 
Could you raise this PR?

**Comment by IowaDave** [comment]
Hello, @designer2k2 

I have a plan to deal with it. The main issue is the duplicative (and misdirective) description in the Library Manager. 

IMHO it would be sufficient for the owner of the repo to modify the description in a way that clearly characterizes the repo a fork and makes it distinct from our repo. He's got to fix the "more info" link to point to his own, also. 

Question for you: does the Library Manager get all of its descriptive info from the library.properties file? Nothing from README or anywhere else, right?

**Step 1**
I plan to start with a PR into the DS3231_RTC repo modifying the library.properties file (and maybe their README also), with a polite explanation and request that they: 
* merge the changes, then 
* publish a new version.

**Step 2**
Give them some time to take appropriate action. If they don't cooperate after a reasonable wait then maybe reach out to the library registry maintenance team with a PR to remove it. They would be able to go look and see that we approached the repo owner first.

I'll get started on Wednesday, March 22.

**Comment by designer2k2** [comment]
Hello @IowaDave,
yes that is a much better way, if the *_RTC changes the repo it would be ok. 

And yes the Library Manager get all of its descriptive info from the library.properties file: https://arduino.github.io/arduino-cli/0.31/library-specification/

**Comment by IowaDave** [comment]
@designer2k2 

Thanks again, Stephan,

You can see the PR here: [https://github.com/affanhanifathtarech/DS3231_RTC/pull/1](https://github.com/affanhanifathtarech/DS3231_RTC/pull/1).

David

**Pull request merged**
