### PR TITLE
Fix handling negative temperatures, fractional temperature, uninitialized const

### PR DESCRIPTION
**Pull request by mike-s123**
There are already 2 PRs for the unitialized const. This also fixes handling of negative temperatures (below 0C), and handles the fractional part of the temperature correctly. Changed the temperature return value for a bad reading to NaN from -9999.

### CODE REVIEW

**Comment by awickert** [comment]
Update to NaN sounds fine.
Keeping: static const char buff[4]={'0','0','0','0'};
If it is better to not state those values for some reason, then we can go with {}.

**Comment by mike-s123** [comment]
Negative temperatures are still BROKEN!!!. NaN is missing in action.

**Comment by awickert** [comment]
Well, we can go back to -9999. That worked, and is obviously an impossible temperature.

**Comment by mike-s123** [comment]
You dismissed my PR, which contained not only the NaN, but a fix for broken temperatures when <0C.

**Comment by awickert** [comment]
You're right! I had thought that I had merged. There's working in the middle of the night for ya... thanks for the catch!

**Pull request merged**
