### PR TITLE
CI by compiling the examples

### PR DESCRIPTION
**Pull request by designer2k2**
Hello,
thanks for this Library, i use it in some projects and it works great for me!
As there is currently no CI here maybe this can help you? 

This PR brings a github action that runs on every push or pull request.  It takes the current state of the repository and compiles every example. It is done using the official arduino "compile-sketch" action: https://github.com/arduino/compile-sketches
It is a minimalistic setup as it compiles only for the default board (Arduino Uno). 
If all examples compiled without error, its considered passing. 

An example run: https://github.com/designer2k2/DS3231/actions/runs/3800802241/jobs/6464618235

grafik

greetings from Austria,
Stephan

### CODE REVIEW

**Comment by IowaDave** [comment]
Hello Stephan,

Thank you for offering this PR. I want to acknowledge it, even though I do not see myself in a position to decide about merging it. I shall leave that decision to the people who built and own the repo.

Happy to address questions about the documentation. That's where my two cents' worth of effort went.

Again, thanks, and happy new year!

David

**Comment by awickert** [comment]
I'm quite convinced that we'll have loads of failures -- that is, unless @IowaDave, @hasenradball, & co. have replaced the cruft.

I will merge and see how it does : )

Grüße aus der USA (Minnesota)

**Comment by awickert** [comment]
IT PASSED!

To those maintaining this repo while I've been busy professor-ing: AMAZING. I am so gratified. Thank you.

**Comment by IowaDave** [comment]
It's a privilege, Andy.  Thanks!

David

**Pull request merged**
